language: php
php:
- 5.2
- 5.3
- 5.4
- 5.5
env:
- DB=mysql
- DB=pgsql
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
after_success: 
deploy:
  provider: s3
  access_key_id: AKIAILHE4W3F4FJZQBXA
  secret_access_key: IODgIVLnFfW64qMgrOi3422aK6YCHpEiiv5EJr6H
  bucket: vikram-test
region: us-west-2
